//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityZen.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityZen.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CityZen client for Windows Phone!.
        /// </summary>
        public static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityZen.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string FlagCity {
            get {
                return ResourceManager.GetString("FlagCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here.
        /// </summary>
        public static string FlagPosMap {
            get {
                return ResourceManager.GetString("FlagPosMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string FlagRoad {
            get {
                return ResourceManager.GetString("FlagRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag a problem.
        /// </summary>
        public static string FlagTitle {
            get {
                return ResourceManager.GetString("FlagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the problem?.
        /// </summary>
        public static string FlagWhat {
            get {
                return ResourceManager.GetString("FlagWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you?.
        /// </summary>
        public static string FlagWhere {
            get {
                return ResourceManager.GetString("FlagWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding your position....
        /// </summary>
        public static string MapLoadText {
            get {
                return ResourceManager.GetString("MapLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning system is not enabled. Please enable it and retry.
        /// </summary>
        public static string MsgBxErrBody {
            get {
                return ResourceManager.GetString("MsgBxErrBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgBxErrTitle {
            get {
                return ResourceManager.GetString("MsgBxErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string TileSignal {
            get {
                return ResourceManager.GetString("TileSignal", resourceCulture);
            }
        }
    }
}
